version: "3.5"

services:
  web:
    build: 
      context: web
    image: web:latest
    ports: 
    - 8080:80
    
  api:
    build: 
      context: api
    image: api:latest
    # ports: 
    # - 8000:8000
